
apiVersion: v1
kind: Deployment
metadata:
  name: k8s-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-app
    spec:
      containers:
      - name: k8s-app-container
        image: nanajiseelam/hello-image:latest
        ports:
        - containerPort: 8080
      
---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: k8s-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
