apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-image
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 2
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello-image
          image: nanajiseelam/hello:latest
          ports:
            - containerPort: 8089


---

apiVersion: v1
kind: Service
metadata:
  name: hellosvc
spec:
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: LoadBalancer
